<a href="https://colab.research.google.com/github/DCCP-Hugo/diplomado/blob/master/1_Librer%C3%ADa_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='blue'>**Librería NumPy**</font>

**NumPy**  asdasdasdas es la librería por excelencia para computación científica en Python. Integra muchas funciones de cálculo matricial de N dimensiones, y una variedad de rutinas para operaciones rápidas en matrices, que incluyen manipulación matemática, lógica, y de tamaño y forma, clasificación, selección, I/O, transformada de Fourier, algebra lineal, operaciones estadísticas, simulación aleatoria y muchas otras.

<img src='https://drive.google.com/uc?export=view&id=1_foOq3ZJE-GKzm9hDpuTDrT8c_YxkorY' width="400" align="center" style="margin-right: 20px">

En el núcleo del paquete NumPy está el objeto **ndarray**. Este encapsula matrices n-dimensionales de tipos de datos homogeneos, con muchas operaciones que se realizan en código compilado (lenguaje C) para mejorar el rendimiento. Es la librería de cálculo más popular debido a su facilidad de uso y la rapidez de sus cálculos.

Existen varias diferencias importantes entre las matrices de NumPy y las secuencias estándar de Python:

* Las matrices NumPy **tienen un tamaño fijo** al momento de la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un ndarray creará una nueva matriz y eliminará la original.


* Se requiere que todos los elementos de una matriz NumPy correspondan al mismo tipo de datos y, por lo tanto, tendrán el mismo tamaño en la memoria. La excepción: uno puede tener matrices de objetos (Python, incluido NumPy), lo que permite matrices de elementos de diferentes tamaños.


* Las matrices NumPy facilitan las operaciones matemáticas avanzadas y las de otro tipo, en grandes cantidades de datos. Por lo general, estas operaciones se ejecutan de manera más eficiente y con menos código que al usar las secuencias integradas de Python.


* Una multitud de paquetes científicos y matemáticos basados en Python utilizan matrices NumPy; aunque estos paquetes suelen admitir la entrada de secuencias estándar de Python, convierten dicha entrada en matrices NumPy antes del procesamiento y, a menudo, generan matrices NumPy. En otras palabras, para usar de manera eficiente gran parte (quizás incluso la mayoría) del software científico/matemático basado en Python de hoy en día, simplemente saber cómo usar los tipos de secuencia incorporados de Python es insuficiente; uno también necesita saber cómo usar las matrices NumPy.

## <font color='blue'>**Instalando NumPy**</font>

Para instalar NumPy, se recomienda utilizar una distribución científica de Python. Las instrucciones completas para instalar NumPy en sus sistemas operativos, las pueden encontrar en <a href=”https://www.scipy.org/install.html”>https://www.scipy.org/install.html</a>.

Si ya tienes Python, puedes instalar NumPy con:



```
conda install numpy
```



o

```
pip install numpy
```

Si aún no tiene Python instalado &#128544; &#128544; &#128544;, se recomienda utilizar **Anaconda**. Es la forma más sencilla de empezar. Lo bueno de obtener esta distribución es el hecho de que no necesita preocuparse demasiado por instalar NumPy por separado o cualquiera de los paquetes principales que utilizará para sus análisis de datos, como pandas, Scikit-Learn, entre otras.

Puede encontrar todos los detalles de instalación en la sección Instalación en <a href=”https://www.scipy.org/install.html”>SciPy</a>. 

### <font color='blue'>**¿Cómo importar NumPy?**</font>

Siempre que desee utilizar un paquete o una biblioteca en su código, **primero debe hacerlo accesible**.

Para comenzar a usar NumPy y todas las funciones disponibles en NumPy, necesitará importarlo. Esto se puede hacer fácilmente con esta declaración de importación:

In [ ]:
import numpy as np

Acortamos el nombre **numpy** a **np** para ahorrar tiempo y para mantener el código legible para que cualquiera que trabaje con su código pueda entenderlo y ejecutarlo fácilmente.

### <font color='blue'>**¿Cuál es la diferencia entre una lista y un matriz NumPy?**</font>

NumPy ofrece una enorme variedad de formas rápidas y eficientes de crear matrices y manipular datos numéricos. Si bien una lista de Python puede contener diferentes tipos de datos dentro de una sola lista, todos los elementos de una matriz NumPy deben ser homogéneos. Las operaciones matemáticas que deben realizarse en matrices serían extremadamente ineficaces si las matrices no fueran homogéneas.

#### <font color='blue'>**¿Por qué usar NumPy?**</font>

Las matrices NumPy son más rápidas y compactas que las listas de Python. Una matriz consume menos memoria. NumPy usa mucha menos memoria para almacenar datos y proporciona un mecanismo para especificar los tipos de datos. Esto permite optimizar aún más el código.

In [ ]:
import sys

S = range(10000)
print('Resultado de memoria asignada a la lista de Python:')
print(sys.getsizeof(5)*len(S))
print()
D=np.arange(10000)
print('Resultado de memoria asignada a NumPy array:')
print(D.size*D.itemsize)

Resultado de memoria asignada a la lista de Python:
280000

Resultado de memoria asignada a NumPy array:
80000


In [ ]:
import time
SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print('Resultado test de velocidad para lista de Python [ms]:')
print((time.time()-start)*1000)
print()

start = time.time()
result = A1+A2
print('Resultado test de velocidad para NumPy array [ms]:')
print((time.time()-start)*1000)


Resultado test de velocidad para lista de Python [ms]:
277.3613929748535

Resultado test de velocidad para NumPy array [ms]:
49.23558235168457


### <font color='blue'>**¿Qué es un matriz?**</font>

Una matriz (o arreglo) es la estructura de datos central de la biblioteca NumPy. Una matriz es una cuadrícula de valores y contiene información sobre los datos sin procesar, cómo ubicar un elemento y cómo interpretar un elemento. Tiene una cuadrícula de elementos que se pueden indexar de varias formas. Los elementos son todos del mismo tipo, denominados **array dtype**.

<img src='https://drive.google.com/uc?export=view&id=1gzNzhv_B2Dcu5NzozSAXqmNp3zio6Mc1' width="500" align="center" style="margin-right: 20px">

**Nota: es posible referirse la estructura ndarray de NumPy de las siguientes formas: array, arreglo, y/o matriz.**

Una matriz puede ser indexada por una tupla de enteros no negativos, por booleanos, por otra matriz o por enteros. El rango de la matriz es el número de dimensiones. La forma de la matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Una forma en que podemos inicializar matrices NumPy es a partir de listas de Python, utilizando listas anidadas para datos bidimensionales o de mayor dimensión. Por ejemplo:


In [ ]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


o

In [ ]:
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])
print(A)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


Podemos acceder a los elementos de la matriz utilizando **corchetes**. Cuando acceda a los elementos de la matriz, recuerde que la **indexación en NumPy comienza en 0**. Eso significa que si desea acceder al primer elemento de su matriz, estará accediendo al elemento "0".

<img src='https://drive.google.com/uc?export=view&id=18qtkEag596pYiUWuULj1f88v4L-1DEnq' width="500" align="center" style="margin-right: 20px">

In [ ]:
print(A[0])

[1 2 3]


In [ ]:
print(A[2,1])

14


In [ ]:
#Observación:
#Para una columna, fijar el : para traer todos los elementos
print(A[:,2])


[ 3  9 15 21]


Una matriz N-dimensional es una matriz con cualquier número de dimensiones. También puede encontrar matrices 1D o matriz unidimensional, 2D o matriz bidimensional, etc.

La clase ndarray de NumPy se utiliza para representar tanto matrices como vectores. Un vector es una matriz con una sola dimensión (no hay diferencia entre los vectores de fila y columna), mientras que una matriz se refiere a una matriz con dos dimensiones. Para matrices tridimensionales o superiores, el término tensor también se usa comúnmente.

#### <font color='blue'>**¿Cuáles son los atributos de una matriz?**</font>

Una matriz suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. El número de dimensiones y elementos de una matriz se define por su forma. La forma de una matriz es una tupla de números enteros no negativos que especifican los tamaños de cada dimensión.

En NumPy, las dimensiones se llaman ejes. Esto significa que si tiene una matriz 2D que se ve así:

In [ ]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Su matriz tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.

Al igual que en otros objetos contenedores de Python, se puede acceder y modificar el contenido de una matriz indexando o dividiendo la matriz. A diferencia de los objetos contenedores típicos, diferentes matrices pueden compartir los mismos datos, por lo que los cambios realizados en una matriz pueden ser visibles en otra.

Los atributos de la matriz reflejan información intrínseca a la propia matriz. Si necesita obtener, o incluso establecer, propiedades de una matriz sin crear una nueva matriz, a menudo puede acceder a una matriz a través de sus atributos. Para detalles y más información pinche <a href=”https://numpy.org/devdocs/reference/arrays.ndarray.html#arrays-ndarray”>aquí</a>. 

## <font color='green'>**Ejercicio 1**</font>

A partir de la matriz A definida anteriomente:

1. Indicar el rango y la forma de la matriz A.
1. Crear un vector *a1* que corresponda a la segunda columna de la matriz A.
1. Crear una matriz *a2* que incluya los elementos de las filas 2 a 4 y de las columnas 2 a 3 de la matriz A.
1. Crear un vector *a3* que contenga los elementos A[0,0], A[1,2], A[0,1], A[3,2], A[2,3] y A[1,1]
1. Crear una matriz *a4* de 2x2 con las primeras dos filas.
1. crear una matriz *a5* que contenga la última y la primera fila de la matriz A.

In [ ]:
#Solución
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])

dimensiones = A.ndim
#print(dimensiones)

tamano = A.size
#print(tamano)

a1 = A[:,1]
#print(a1)

#a2 = np.array(A[1:4,2:3] )
a2 = np.array(A[1:3,1:2])
print(a2)

a3 = np.array([A[0,0], A[1,2] , A[0,1] , A[3,2] , A[2,2] , A[1,1]])
print(a3)
#a4 = np.array( [A[0:1,0:1], A[1:2,1:2]])
#print(a4)
a5 = np.array([A[3], A[0]] )
print(a5)

[[ 8]
 [14]]
[ 1  9  2 21 15  8]
[[19 20 21]
 [ 1  2  3]]


## <font color='green'>**Fin ejercicio 1**</font>

## <font color='blue'>**Creando vectores y matrices** </font>

Para crear una matriz NumPy, se puede utilizar la función **np.array()**.

Todo lo que necesita hacer para crear una matriz simple es pasarle una lista. Si lo desea, también puede especificar el tipo de datos en su lista.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4, 5, 6]])
c = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(a)
print()
print(b)
print()
print(c)

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Además de crear una matriz a partir de una secuencia de elementos, puede crear fácilmente un vector o una matriz llena de ceros:

In [ ]:
vector_ceros = np.zeros(5)
matriz_ceros = np.zeros((2,5))
print(vector_ceros)
print()
print(matriz_ceros)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


o un vector o matriz de 1s:

In [ ]:
vector_unos = np.ones(5)
matriz_unos = np.ones((2,5))
print(vector_unos)
print()
print(matriz_unos)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


o un vector o matriz vacía. La función vacía crea una matriz cuyo contenido inicial es aleatorio y depende del estado de la memoria. La razón para usar vacío sobre ceros (o algo similar) es la velocidad, ¡solo asegúrese de completar todos los elementos después! &#128521; &#128521; &#128521;.

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

También es posible crear un vector con elementos dentro de un rango:

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

Un vector que contiene un rango de intervalos espaciados uniformemente. Para hacer esto, debe especificar el primer número, el último número y el tamaño del paso.

In [ ]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

También puede utilizar **np.linspace()** para crear una matriz con valores espaciados linealmente en un intervalo especificado:

In [ ]:
np.linspace(0, 15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

El tipo de datos predeterminado es punto flotante (*np.float64*), pero es posible especificar explícitamente qué tipo de datos desea, utilizando la palabra clave **dtype**. Para más información sobre tipo de datos, pinche <a href=”https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes”>aquí</a>.

In [ ]:
x = np.ones(5, dtype=np.int64)
x

array([1, 1, 1, 1, 1])

La matriz de identidad es una matriz cuadrada con unos en la diagonal principal:

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## <font color='blue'>**Operaciones con matrices**</font>

Las operaciones básicas son simples con NumPy. Una vez que ha creado sus matrices, puede comenzar a trabajar con ellas. Por ejemplo, se han creado dos matrices, una llamada *a* y otra llamada *b*.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 3, 6, 8, 1], dtype=int)
a + b

array([11,  5,  9, 12,  6])

Si desea encontrar la suma de los elementos en una matriz, debe usar **sum()**. Esto funciona para matrices 1D, matrices 2D y matrices en dimensiones más altas.

In [ ]:
a = np.array([1, 2, 3, 4])
a.sum()

10

Para realizar esta operación en más dimensiones, debe especificar el eje.

In [ ]:
b = np.array([[1, 1], [2, 2]])


array([[1, 1],
       [2, 2]])

Para sumar por filas:

In [ ]:
b.sum(axis=0)

array([3, 3])

Para sumar por columnas:

In [ ]:
b.sum(axis=1)

array([2, 4])

Sustracción:

In [ ]:
a - b

ValueError: ignored

Multiplicación por elementos:

In [ ]:
a = np.array( [[1,1],[2,1]] )
b = np.array( [[2,4],[3,4]] )
a * b

array([[2, 4],
       [6, 4]])

Multiplicación de matrices: se puede realizar utilizando el operador @ (en python> = 3.5) o la función o método **dot**:

In [ ]:
a @ b

array([[ 5,  8],
       [ 7, 12]])

In [ ]:
a.dot(b)

array([[ 5,  8],
       [ 7, 12]])

División:

In [ ]:
a / b

array([[0.5       , 0.25      ],
       [0.66666667, 0.25      ]])

Otras operaciones:

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)
#Elevar a una potencia
c = b**2
print(c)
print()
#Función seno
c = 10*np.sin(a)
print(c)
print()
#Funciones lógicas
c = a < 35
print(c)

[0 1 4 9]

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]

[ True  True False False]


In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
...              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
...              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
#Mínimo
b = a.min()
print(b)
print()
#Máximo
b = a.max()
print(b)
print()
#Máximo por columna
b = a.max(axis=1)
print(b)
print()
#Media
b = a.mean()
print(b)
print()
#Desviación estándar
b = a.std()
print(b)
print()

0.05093587

0.82485143

[0.5510652  0.55645993 0.82485143]

0.4049648666666667

0.21392120766089617



NumPy contiene una batería de operaciones sobre matrices: aritméticas, operaciones binarias, estadísticas, funciones, entre otras. Para más información, pinche <a href=”https://numpy.org/devdocs/user/quickstart.html#the-basics”>aquí</a>.

La generación de números aleatorios es una parte importante en la configuración y evaluación de muchos algoritmos de aprendizaje automático. Ya sea que necesite inicializar pesos aleatoriamente en una red neuronal artificial, dividir datos en conjuntos aleatorios o mezclar aleatoriamente su conjunto de datos, es esencial poder generar números aleatorios (en realidad, números pseudoaleatorios repetibles).

Con **Generator.integers**, puede generar números enteros aleatorios. Puede generar una matriz de 2 x 4 de números enteros aleatorios entre 0 y 4 con:

In [ ]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[1, 2, 4, 3],
       [2, 3, 3, 3]])

Con la clase **random.Generator** puede generar números aleatorios:

In [ ]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

Algunas operaciones, como += y *=, actúan para modificar una matriz existente en lugar de crear una nueva.

In [ ]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
print(a)
print()
b += a
print(b)

[[3 3 3]
 [3 3 3]]

[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


Es posible realizar una operación entre una matriz y un solo número (operación entre un vector y un escalar) o entre matrices de dos tamaños diferentes. Por ejemplo:

In [ ]:
distancia_millas = np.array([1.0, 2.0])
distancia_km = distancia_millas * 1.6
print(distancia_km)

[1.6 3.2]


## <font color='green'>**Ejercicio 2**</font>

1. Crear una matriz de 4x9 que esté inicializa con el valor 3.5.
1. Crear un vector de longitud 4.
1. Crear una matriz de rango 4.
1. Crear una matriz de dos dimensiones en que una dimensión represente el sexo y la otra la edad de los integrantes del grupo. Luego, convertir la dimensión edad en años a la edad en meses.
1. Generar una matriz de 7 por 9. Las primeras 3 columnas de la matriz tienen que tener el valor 0. La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7.Las otras tres columnas deben tener el valor 1.

In [ ]:
#Solución
a1 = np.ones((4,9))
a1[0,0] = 3.5
print(a1)

b = np.arange(4)
print()
print(b)

c = 
d = np.array([ np.zeros(7) ,[31,23,45,67,78,23,12] ])
print()
print(d)

e1 = np.zeros((7,3))


[[3.5 1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]]

[0 1 2 3]

[[ 0.  0.  0.  0.  0.  0.  0.]
 [31. 23. 45. 67. 78. 23. 12.]]


In [ ]:
e1 = np.zeros((7,3))
e2 = np.ones(6)*0.5  
#e2.append(0.7)
#np.append(e2, 0.7, axis=None)
e2 = np.append(e2, 0.7)

#e3 = np.vstack((e1,e2)).T
#e3 =np.append(e1, e2, axis=0)

#b[:,:-1] = a
print(e1)
print(e2)
print()
#print(e3)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.5 0.5 0.5 0.5 0.5 0.5 0.7]



## <font color='green'>**Fin ejercicio 2**</font>

## <font color='blue'>**Ordenar y agregar elementos a una matriz**</font>

Ordenar un elemento es simple con **np.sort()**. Puede especificar el eje, el tipo y el orden cuando llama a la función.

In [ ]:
arr = np.array([2, 1, 5, 10, 3, 7, 4, 9, 6, 8])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

Para agregar elementos, se utiliza la función **np.concatenate()**:

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

#Observación: No funciona con axis = 1

array([[1, 2],
       [3, 4],
       [5, 6]])

## <font color='blue'>**Forma y Tamaño de una matriz**</font>

**ndarray.ndim** entrega el número de ejes, o dimensiones, de la matriz.

**ndarray.size** entrega el número total de elementos de la matriz.

**ndarray.shape** entrega una tupla de números enteros que indican el número de elementos almacenados a lo largo de cada dimensión de la matriz. Si, por ejemplo, tiene una matriz 2D con 2 filas y 3 columnas, la forma de su matriz es (2, 3).

Por ejemplo:

In [ ]:
arr_ejemplo = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [ ]:
arr_ejemplo.ndim

3

In [ ]:
arr_ejemplo.size

24

In [ ]:
arr_ejemplo.shape

(3, 2, 4)

## <font color='blue'>**Redimensionamiento de matrices**</font>

El uso de **arr.reshape()** le dará una nueva forma a una matriz sin cambiar los datos. Recuerde que cuando usa el método de redimensionamiento, la matriz que desea generar debe tener la misma cantidad de elementos que la matriz original. Si comienza con una matriz con 12 elementos, deberá asegurarse de que su nueva matriz también tenga un total de 12 elementos.

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


## <font color='blue'>**Transponer una matriz**</font>

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

## <font color='blue'>**¿Cómo agregar nuevos ejes (dimensiones) a una matriz?**</font>

Con las funcionaes **np.newaxis** y **np.expand_dims** se puede aumentar las dimensiones de su matriz existente.

El uso de **np.newaxis** aumentará las dimensiones de su matriz en una dimensión cuando se use una vez. Esto significa que una matriz 1D se convertirá en una matriz 2D, una matriz 2D se convertirá en una matriz 3D, y así sucesivamente. Por ejemplo:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a.shape

(7,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 7)

Es posible convertir explícitamente una matriz 1D a un vector de fila o a un vector de columna usando **np.newaxis**. Por ejemplo, puede convertir una matriz 1D en un vector de fila insertando un eje a lo largo de la primera dimensión:

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 7)

o convertirlo en un vector columna, insertando un ejer en la segundo dimensión:

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(7, 1)

También es posible expandir una matriz insertando un nuevo eje en una posición específica con la función **np.expand_dims()**:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## <font color='blue'>**Elementos únicos y conteo**</font>

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
valores_unicos = np.unique(a)
print(valores_unicos)

[11 12 13 14 15 16 17 18 19 20]


Para obtener los índices de los valores únicos en una matriz NumPy se debe usar el argumento **return_index** en la función **np.unique()**:

In [ ]:
valores_unicos, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


Puede pasar el argumento **return_counts** en **np.unique()** junto con su matriz para obtener el recuento de frecuencia de valores únicos en una matriz de NumPy:

In [ ]:
valores_unicos, contar_ocurrencia = np.unique(a, return_counts=True)
print(contar_ocurrencia)

[3 2 2 2 1 1 1 1 1 1]


## <font color='blue'>**Aplicar una función sobre una fila o columna de una matriz**</font>

La función **np.apply_along_axis()** permite aplicar una función sobre una de las dimisiones de un matriz. Por lo que es una herramienta con muchas posibilidades. La función tiene tres parámetros, en el primero se indica la función que se desea aplicar, en la segunda el eje sobre el que se desea aplicar la función y finalmente la matriz. Obteniéndose como salida de la función una matriz con un eje menos que el original.

Por ejemplo:

In [ ]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)
np.apply_along_axis(sum, 0, arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [ ]:
#Función que calcula el promedio entre el primero y el último elemento de un vector
def my_func(a):
    return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(my_func, 0, b)

array([4., 5., 6.])

In [ ]:
np.apply_along_axis(my_func, 1, b)

array([2., 5., 8.])

## <font color='green'>**Ejercicio 3**</font>

Crear un matriz bidimensional 5x5 con todos los valores cero. Usando el indexado de matrices, asignar 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asignar el valor 100 a todos los elementos de la subamatriz central de 3x3 de la matriz de 5x5.

In [ ]:
#Solución
zero = np.zeros((5,5))
print(zero)

zero[4,:] = 1
print()
print(zero)

zero[:,0] = 5
print()
print(zero)

zero[1:4,1:4] = 100
print()
print(zero)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]

[[5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 1. 1. 1. 1.]]

[[  5.   0.   0.   0.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5.   1.   1.   1.   1.]]


## <font color='green'>**Fin ejercicio 3**</font>

## <font color='green'>**Ejercicio 4**</font>

Los diámetros de las esporas del lycopodium pueden medirse por métodos interferométricos &#129299; &#129299; &#129299;. Los resultados de uno de estos experimentos son los siguientes:

<img src='https://drive.google.com/uc?export=view&id=1te4LaaTF_WzyjPShqDOMnP9qDiswwZGG' width="500" align="center" style="margin-right: 20px">

donde $k$ = 5880.

Calcular, usando funciones de NumPy, el diámetro medio de las esporas y la desviación estándar de la muestra. Separar, en matrices independientes, las medidas de los diámetros:

* Que tengan valores inferiores a la media ($\mu$) menos la desviación estándar ($\sigma$), es decir $d < \mu_{d} - \sigma_{d}$
* Que tengan valores superiores a la media más la desviación estándar, es decir $d > \mu_{d} + \sigma_{d}$
* Que tengan valores entre $\mu_{d} - \sigma_{d} < d < \mu_{d} + \sigma_{d}$

**Adaptado de Curso de Computación Científica, J. Pérez, T. Roca y C. López**

In [ ]:
#Solución



## <font color='green'>**Fin ejercicio 4**</font>